# Generated by Django 5.2.5 on 2025-10-13 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='joboffer',
            name='main_technology',
            field=models.CharField(blank=True, help_text='główna technologia z wyszukiwania', max_length=100, null=True),
        ),
    ]
