# Generated by Django 5.2.5 on 2025-08-29 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalinfo',
            name='profile_picture',
            field=models.URLField(blank=True, null=True),
        ),
    ]
