# Generated by Django 5.2.7 on 2025-10-22 21:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_joboffer_main_technology'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScraperTechnologyFilter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(help_text="Identyfikator platrofmy, np. 'justjoinit' ablo 'nofloffjobs'.", max_length=50)),
                ('value', models.CharField(help_text='Slug/filtr przekazany do scrapera.', max_length=100)),
                ('technology', models.ForeignKey(help_text='Technologia widoczna w formularzu', on_delete=django.db.models.deletion.CASCADE, related_name='platform_filters', to='myapp.scrapertechnology')),
            ],
            options={
                'verbose_name': 'Filtr technologii dla platformy',
                'verbose_name_plural': 'Filtry technologii dla platform',
                'unique_together': {('technology', 'platform')},
            },
        ),
    ]
