# Generated by Django 5.2.5 on 2025-08-29 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_personalinfo_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalinfo',
            name='profile_picture',
            field=models.ImageField(blank=True, help_text='Wgraj swoje zdjęcie profilowe', null=True, upload_to='profile_pictures/'),
        ),
    ]
