# Generated by Django 5.2.5 on 2025-09-01 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_personalinfo_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='created_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
