# Generated by Django 5.2.7 on 2025-10-22 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_scrapertechnologyfilter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrapertechnologyfilter',
            name='platform',
            field=models.CharField(help_text="Identyfikator platformy, np. 'justjoinit' albo 'nofluffyjobs'.", max_length=50),
        ),
    ]
