# Generated by Django 5.2.5 on 2024-09-08 12:00

from django.db import migrations
from django.utils.text import slugify


def populate_slugs(apps, schema_editor):
    """
    Generate a unique slug for each existing Project.
    """
    Project = apps.get_model('myapp', 'Project')
    for project in Project.objects.all():
        if not project.slug:
            base_slug = slugify(project.title)
            unique_slug = base_slug
            counter = 1
            # Append a number if the slug already exists
            while Project.objects.filter(slug=unique_slug).exists():
                unique_slug = f'{base_slug}-{counter}'
                counter += 1
            project.slug = unique_slug
            project.save()


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_project_slug_alter_project_created_date'),  # Change '0004_project_slug' to your previous migration file name
    ]

    operations = [
        migrations.RunPython(populate_slugs, migrations.RunPython.noop),
    ]