# Generated by Django 5.2.5 on 2025-09-01 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_populate_projects_slugs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=200, unique=True),
            preserve_default=False,
        ),
    ]
