# Generated by Django 5.2.5 on 2025-09-03 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_project_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='JourneyStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200)),
                ('date', models.DateField(help_text='Estimated start date')),
                ('order', models.PositiveIntegerField(default=0, help_text='The displaying order (0 as the first)')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
