# Generated by Django 5.2.5 on 2025-10-02 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_journeystep'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('company', models.CharField(blank=True, max_length=255, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('url', models.URLField(max_length=500, unique=True)),
                ('source', models.CharField(max_length=100)),
                ('scraped_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-scraped_date'],
            },
        ),
    ]
