# Generated by Django 5.2.5 on 2025-10-02 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_joboffer'),
    ]

    operations = [
        migrations.AddField(
            model_name='joboffer',
            name='salary',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='joboffer',
            name='skills',
            field=models.TextField(blank=True, null=True),
        ),
    ]
