# Generated by Django 5.2.5 on 2025-10-06 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_joboffer_salary_joboffer_skills'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScraperTechnology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='technology name for eg. python', max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Technologia Scrapera',
            },
        ),
    ]
