# Generated by Django 5.2.5 on 2025-10-06 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_scrapertechnology'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scrapertechnology',
            options={'ordering': ['name'], 'verbose_name': 'Technologia Scrapera', 'verbose_name_plural': 'Technologie Scrapera'},
        ),
    ]
