# Generated by Django 5.2.5 on 2025-10-06 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_alter_scrapertechnology_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='joboffer',
            name='experience_level',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
