# Generated by Django 5.2.5 on 2025-10-07 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_joboffer_experience_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='joboffer',
            name='date_posted',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
