# Generated by Django 5.2.5 on 2025-10-07 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_joboffer_date_posted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joboffer',
            name='date_posted',
            field=models.DateField(blank=True, null=True),
        ),
    ]
